# Generated by Django 5.1 on 2025-02-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_alter_estate_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='owner_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Собственник (имя)'),
        ),
    ]
