# Generated by Django 5.1 on 2025-02-25 13:23

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0003_alter_estate_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Телефон 1'),
        ),
    ]
